(function (AB) {
  AB.GAME_CONFIG = {
    board: {
      cols: 8,
      rows: 6,
      playerStartRow: 3,
      tileSize: 86,
      offsetX: 206,
      offsetY: 32,
    },
    benchSize: 8,
    playerStartGold: 10,
    playerStartHp: 30,
    aiStartGold: 10,
    aiStartHp: 30,
    startLevel: 3,
    maxLevel: 8,
    xpPerBuy: 4,
    xpCost: 4,
    refreshCost: 2,
    levelThresholds: {
      3: 6,
      4: 10,
      5: 18,
      6: 28,
      7: 40,
      8: 0,
    },
    phaseDurations: {
      Preparation: 2,
      Shop: 12,
      Placement: 28,
      Reward: 4,
    },
    combat: {
      maxSeconds: 45,
      manaOnAttack: 12,
      manaOnHit: 8,
      attackPoseTime: 0.2,
      defendPoseTime: 0.18,
      deathHoldTime: 1.2,
    },
    economy: {
      baseIncome: 5,
      winBonus: 1,
      lossBonus: 2,
      maxInterest: 5,
    },
    combatSpeeds: [1, 1.5, 2],
  };
})(window.AutoBattler = window.AutoBattler || {});
