(function (AB) {
  AB.UNIT_CONFIG = {
    knight: {
      id: "knight",
      name: "Knight",
      cost: 1,
      rarity: "Common",
      hp: 650,
      attackDamage: 54,
      attackSpeed: 0.82,
      attackRange: 1,
      movementSpeed: 2,
      armor: 34,
      mana: 80,
      abilityPower: 72,
      ability: {
        id: "shield-bash",
        name: "Shield Bash",
        description: "Bashes one enemy, dealing damage and briefly stunning them.",
      },
      className: "Warrior",
      origin: "Guardian",
    },
    archer: {
      id: "archer",
      name: "Archer",
      cost: 2,
      rarity: "Uncommon",
      hp: 420,
      attackDamage: 68,
      attackSpeed: 1.1,
      attackRange: 4,
      movementSpeed: 2.05,
      armor: 12,
      mana: 70,
      abilityPower: 88,
      ability: {
        id: "piercing-shot",
        name: "Piercing Shot",
        description: "Fires through the target and hits one enemy behind them.",
      },
      className: "Ranger",
      origin: "Elf",
    },
    mage: {
      id: "mage",
      name: "Mage",
      cost: 3,
      rarity: "Rare",
      hp: 390,
      attackDamage: 42,
      attackSpeed: 0.76,
      attackRange: 4,
      movementSpeed: 1.8,
      armor: 8,
      mana: 80,
      abilityPower: 115,
      ability: {
        id: "arcane-orb",
        name: "Arcane Orb",
        description: "Launches an orb that explodes around the target.",
      },
      className: "Mage",
      origin: "Undead",
    },
    dwarf: {
      id: "dwarf",
      name: "Dwarf Guardian",
      cost: 2,
      rarity: "Uncommon",
      hp: 780,
      attackDamage: 46,
      attackSpeed: 0.68,
      attackRange: 1,
      movementSpeed: 1.6,
      armor: 46,
      mana: 70,
      abilityPower: 120,
      ability: {
        id: "stone-guard",
        name: "Stone Guard",
        description: "Gains a shield and taunts nearby enemies.",
      },
      className: "Warrior",
      origin: "Guardian",
    },
    assassin: {
      id: "assassin",
      name: "Assassin",
      cost: 3,
      rarity: "Rare",
      hp: 440,
      attackDamage: 82,
      attackSpeed: 1.24,
      attackRange: 1,
      movementSpeed: 2.35,
      armor: 12,
      mana: 60,
      abilityPower: 130,
      ability: {
        id: "shadow-strike",
        name: "Shadow Strike",
        description: "Jumps to the backline and lands a critical strike.",
      },
      className: "Assassin",
      origin: "Undead",
    },
  };
})(window.AutoBattler = window.AutoBattler || {});
